name: "Lesson 1 - Exercise 3"

run-name: Run of the complex workflow

on:
  # Workflow run trigger events
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Manually trigger workflow run
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -name: configure NodeJS version 18.* 
  # First job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # By default, the runner will use Bash on Linux/MacOS runners
      # Bash is supported on all runner types
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          name:  install and configure NodeJS 
          run: node -e "console.log('running from node!')"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
